Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
# the path function, which is needed when mapping URLs to views
from django.urls import path

# the dot tells Python to import the views.py module from the same directory as the current urls.py module
from . import views
import pizzas

# the variable app_name helps Django distinguish this urls.py file from files of the same name in other apps within the project
app_name = 'pizzas'

# the variable urlpatterns in this module is a list of individual pages that can be requested from the pizzas app
urlpatterns = [
    path('', views.index, name = 'index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),
]

pizzas/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm
from .models import Pizza

# Create your views here.

def index(request):
    '''The Home Page for Pizzeria.'''
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('name')

    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all() # foreign key is accessed using '_set'
    comments = pizza.comment_set.all()

    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = CommentForm()
    else:
        # POST data submitted, process data
        form = CommentForm(data=request.POST)
        # check to see if all required fields have been filled
        if form.is_valid():
            # write the data from the form to the database
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>Pizzeria</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index' %}">Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas' %}">Pizzas</a></li>
        </div>

    </nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block page_header %}

<img class="mx-auto d-block" src="https://i.redd.it/uknes805x5j71.jpg" width='500' height='200'>
<div class="jumbotron">
    <h1 class="display-3">Think Pizza, Think Katie's</h1>
    <p class="lead">Pizzeria shows you a list of our available pizzas, lists the toppings on each pizza, and allows visitors
        to post comments about any particular pizza.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'pizzas:pizzas' %}" role="button">View Our Menu &raquo;</a>
</div>
<img class="mx-auto d-block" src="https://www.945bayfm.com/wp-content/uploads/2020/02/pizzas-640x400.jpg" width='1000' height='500'>

{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}


<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<h3><p>Pizza: {{ pizza }}</p></h3>
{% if pizza.name == 'Hawaiian' %}
<img src="https://www.jessicagavin.com/wp-content/uploads/2020/07/hawaiian-pizza-16-1024x1536.jpg" width='200' height='200'>
{% elif pizza.name == 'Meat Lovers' %}
<img src="https://myfoodbook.com.au/sites/default/files/styles/sr_wd/public/recipe_photo/Whisk_PI_190919_Pizzas_006_MEAT_LOVERS.jpg" width='260' height='170'>
{% elif pizza.name == 'Margherita' %}
<img src="https://images.crateandbarrel.com/is/image/Crate/frame-margherita-pizza-1" width='250' height='200'>
{% elif pizza.name == 'Supreme' %}
<img src="https://cdn-bpndg.nitrocdn.com/CpZMPKwGohqOxAgaGybHUejVGcoVYwvh/assets/static/optimized/rev-a8eefc3/wp-content/uploads/2021/09/tasty-supreme-pizza-with-olives-peppers-onions-and-sausage-1.jpg" width='200' height='230'>
{% elif pizza.name == 'Four Cheese' %}
<img src="https://www.insidetherustickitchen.com/wp-content/uploads/2020/07/Quattro-Formaggi-1200px-Inside-the-Rustic-Kitchen-2.jpg" width='200' height='230'>
{% endif %}

<h4><p>Toppings:</p></h4>
<ul>
    {% for t in toppings %}

    <li>
        <p>{{ t.name|linebreaks }}</p>
    </li>

    {% empty %}
    <li>There are no toppings for this pizza.</li>
    {% endfor %}
</ul>

<h4><p>Comments:</p></h4>
<ul>
    {% for c in comments %}

    <li>
        <p>{{ c.text|linebreaks }}</p>
    </li>

    {% empty %}
    <li>There are no comments for this pizza.</li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
</p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<h2><p>Pizzas</p></h2>

<ul>
    {% for p in pizzas %}

    <h3><li>
        <a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a>
    </li></h3>

    {% empty %}
    <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}